### PR TITLE
Support selecting a different revision to diff against

### PR DESCRIPTION
**Pull request by vhda**

### CODE REVIEW

**Comment by vhda** [comment]
Hi,

Forgot to warn you that I only tested git. For the remaining VCS I took the required arguments from online documentation.
Do you have any way of testing this across all VCS?

Thanks!

**Comment by tomtom** [comment]
> Do you have any way of testing this across all VCS?

Unfortunately no.

**Comment by vhda** [comment]
You might want to revert the merge until we are sure everything is correct.
I'll try to test on other VCS in the meanwhile, as soon as I have some time.

**Comment by tomtom** [comment]
> You might want to revert the merge until we are sure everything is correct.
> I'll try to test on other VCS in the meanwhile, as soon as I have some time.

Do you have a chance to test this in the foreseeable future? If not, I'd 
rather revert the g:quickfixsigns#vcsdiff#revision param with a more 
general g:quickfixsigns#vcsdiff#extra_args param that can be set to 
whatever you want.

Regards

**Comment by blueyed** [comment]
@vhda @tomtom 
This changes the default behavior, where you only see what is changed relative to the index (`git diff`), but now changes that are staged already (`git add`) show up in the signs still.

To get the old behavior I've tried `let g:quickfixsigns#vcsdiff#revision_git = ''`, but it requires a patch:

```diff
diff --git i/autoload/quickfixsigns/vcsdiff.vim w/autoload/quickfixsigns/vcsdiff.vim
index cf1ffd1..ddb4ced 100644
--- i/autoload/quickfixsigns/vcsdiff.vim
+++ w/autoload/quickfixsigns/vcsdiff.vim
@@ -557,17 +557,11 @@ function! s:GetParam(name, type, default) abort "{{{3
     endif
     let gt = a:name .'_'. a:type
     if exists('g:'. gt)
-        let gtval = g:{gt}
-        if !empty(gtval)
-            return gtval
-        endif
+        return g:{gt}
     endif
     let g = a:name
     if exists('g:'. g)
-        let gval = g:{g}
-        if !empty(gval)
-            return gval
-        endif
+        return g:{g}
     endif
     return a:default
 endf
```

There is no non-empty value to get the old behavior, is there?

**Comment by blueyed** [comment]
@vhda 
What is your use case for this btw?
I can see that is is nice for project specific settings (e.g. via https://github.com/embear/vim-localvimrc), but the initial PR was for the global setting only.

**Comment by vhda** [comment]
@blueyed I noticed that in the meanwhile and have been trying to come up with a different implementation of this feature to overcome that limitation. Give me a day or two more please.

I do frequent commits to keep track of daily updates and sometimes it is desirable to still be able to keep track of what changed during a certain feature implementation. Being able to decide which commit to diff against provides me with that visual aid.

**Comment by vhda** [comment]
Just noticed I already had a patch laying around :)
Let me submit it so that you can try it yourself!

**Comment by vhda** [comment]
Please check my master branch.
@tomtom had made some changes in the meanwhile and I had to rebase my work on top of his.
I still don't like the current solution, because there's some code duplication...

**Comment by blueyed** [comment]
@vhda 
Please create a separate branch and a PR where we can discuss this.

**Comment by tomtom** [comment]
> I can see that is is nice for project specific settings (e.g. via https://github.com/embear/vim-localvimrc), but the initial PR was for the global setting only.

Since commit #bc5bf54211776375b8559376bb0a09fbe05909da the behaviour can also be enabled per buffer, i.e. per project via some kind of project-local init file.

**Comment by tomtom** [comment]
@blueyed I hope https://github.com/tomtom/quickfixsigns_vim/commit/9e10e1527bbfa315bb315daff243329bd35b1af4 captures the gist of your proposal.

**Comment by blueyed** [comment]
@tomtom 
Thanks, that should work!

**Pull request merged**
